############################ GENERAL SETTINGS ############################
#----- API Environments -----#
squareEnv: development
lambdaEnv: development
sagawaEnv: development
#----- VPC Settings -----#
subnetId: subnet-10464166
securityGroupId: sg-75f53413
mongoURI: mongodb://stackinet:7O3xbVbrCWqqlMYt@stackinet-cluster-shard-00-00-wqafo.mongodb.net:27017,stackinet-cluster-shard-00-01-wqafo.mongodb.net:27017,stackinet-cluster-shard-00-02-wqafo.mongodb.net:27017/nj2jp-development?ssl=true&replicaSet=stackinet-cluster-shard-0&authSource=admin
#--------------- DOMAINS ---------------#
baseUrl: http://localhost:3000

#--------------- EMAIL ADDRESSES ---------------#
ctoEmail: tobiah.rex@gmail.com
ceoEmail: tobiah.rex@gmail.com
cdoEmail: diwaakartg@gmail.com
################################# API SETTINGS ###########################
#--------------- AUTH 0 ---------------#
auth0JwtSecret: J-7IXMLuZo5GyvX4jMWgmzlHV-mc22ORaKTZSv2TBPRnabwqTTKSq8p_FAo72wHM
#--------------- MARKET HERO ---------------#
marketHeroApiKey: fb003eda0dc5d73e4a3384252b93da07b109e1cb4ac68ae958f1046126573603
#--------------- Recaptcha ---------------#
recaptchaSecretKey: 6LcQCDMUAAAAAIT1nW_sZ3Jr359bcYaFDS_yietv
#--------------- AWS ---------------#
awsSesRegion: us-east-1
lambdaSecretAccessKey: n4O98Fj3sfFyZJqsEXGhX9yQaSZARa8/Ex9UIUGr
lambdaAccessKeyId: AKIAIZWINLYN3KF5BNWA
#--------------- SQUARE ---------------#
# USA
usSquareLocation: Coffee & Toffee SF
usSquareAccessToken: sq0atp-GSToZCKnR0G3CVfqAWZbPg
usSquareApplicationId: sandbox-sq0idp-YWMJtx9YsEeo6TQjEyASoQ
# JAPAN
jpSquareLocation: ヤマモト 東京
jpSquareAccessToken: sq0atp-a3HpT62fhl3pWOyCfDTppQ
jpSquareApplicationId: sandbox-sq0idp-cAah-f0lBV_8opL4u0agEg
#--------------- JWT TRACKING TOKEN ---------------#
jwtSecret: 4648fyvbgxbasfztzrqewcdmvibopt9e873h4nfic97323gbrjgvivuywtgqvxjcifi
#--------------- SAGAWA ---------------#
sagawaJapanese: TEST1569
sagawaEnglish: TEST1568
#--------------- SLACK ---------------#
slackSupportWebhook: https://hooks.slack.com/services/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
slackErrorNotificationWebhook: https://hooks.slack.com/services/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
slackGeneralNotificationWebhook: https://hooks.slack.com/services/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
